NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### Why NumPy?
- Performance: Operations are implemented in C, making them much faster than pure Python
- Memory efficiency: Compact storage of homogeneous data
- Broadcasting: Automatic handling of different array shapes
- Vectorization: Apply operations to entire arrays at once

In [ ]:
import numpy as np

## 1. Array Creation

NumPy arrays are the core data structure. Unlike Python lists, NumPy arrays are homogeneous (all elements have the same data type) and can be multi-dimensional.


In [ ]:
# Creating arrays from lists
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Type:", type(arr1))

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array with specific data type
arr3 = np.array([1, 2, 3], dtype=np.float64)
print("Float array:", arr3)
print("Data type:", arr3.dtype)


1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
2D Array:
 [[1 2 3]
 [4 5 6]]
Float array: [1. 2. 3.]
Data type: float64


NumPy provides many convenient functions to create arrays with specific patterns:

In [ ]:
# Array of zeros
zeros = np.zeros((3, 4))
print("Zeros array:\n", zeros)

# Array of ones
ones = np.ones((2, 3))
print("Ones array:\n", ones)

# Array with range of values
range_arr = np.arange(0, 10, 2)
print("Range array:", range_arr)

# Linearly spaced array
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

# Identity matrix
identity = np.eye(3)
print("Identity matrix:\n", identity)

# Random arrays
np.random.seed(42)  # For reproducibility
random_arr = np.random.random((2, 3))
print("Random array:\n", random_arr)


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


## 2. Array Properties and Basic Information
Understanding your array's properties is crucial for effective data manipulation.


In [ ]:
# Create a sample array
sample_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:\n", sample_arr)
print("Shape:", sample_arr.shape)
print("Size (total elements):", sample_arr.size)
print("Dimensions:", sample_arr.ndim)
print("Data type:", sample_arr.dtype)
print("Item size (bytes):", sample_arr.itemsize)
print("Total memory (bytes):", sample_arr.nbytes)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size (total elements): 12
Dimensions: 2
Data type: int64
Item size (bytes): 8
Total memory (bytes): 96


### Boolean Indexing
Boolean indexing allows you to select elements based on conditions:


In [ ]:
# Boolean indexing
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition = data > 5
print("Original array:", data)
print("Condition (> 5):", condition)
print("Elements > 5:", data[condition])

# Multiple conditions
complex_condition = (data > 3) & (data < 8)
print("Elements between 3 and 8:", data[complex_condition])

# Modifying values with boolean indexing
data_copy = data.copy()
data_copy[data_copy > 7] = 0
print("Array with values > 7 set to 0:", data_copy)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Condition (> 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]
Elements between 3 and 8: [4 5 6 7]
Array with values > 7 set to 0: [1 2 3 4 5 6 7 0 0 0]


## 4. Array Operations
NumPy's power comes from its ability to perform operations on entire arrays efficiently.


### Element-wise Operations

In [ ]:
# Element-wise operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Array a:", a)
print("Array b:", b)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)
print("Square root:", np.sqrt(a))


Array a: [1 2 3 4]
Array b: [5 6 7 8]
Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Power: [ 1  4  9 16]
Square root: [1.         1.41421356 1.73205081 2.        ]


### Universal Functions (ufuncs)
Universal functions operate element-wise on arrays:


In [ ]:
# Mathematical functions
x = np.array([0, 30, 45, 60, 90])
radians = np.radians(x)

print("Angles in degrees:", x)
print("Angles in radians:", np.round(radians, 3))
print("Sine values:", np.round(np.sin(radians), 3))
print("Cosine values:", np.round(np.cos(radians), 3))

# Other mathematical functions
values = np.array([1, 2, 3])
print("Exponential:", np.exp(values))
print("Natural log:", np.log([1, np.e, np.e**2]))
print("Absolute values:", np.abs([-1, -2, 3, -4]))


Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.    0.524 0.785 1.047 1.571]
Sine values: [0.    0.5   0.707 0.866 1.   ]
Cosine values: [1.    0.866 0.707 0.5   0.   ]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0. 1. 2.]
Absolute values: [1 2 3 4]


### Broadcasting
Broadcasting allows operations between arrays of different shapes:


In [ ]:
# Broadcasting examples
scalar = 5
array_1d = np.array([1, 2, 3, 4])
array_2d = np.array([[1, 2], [3, 4]])

print("Scalar + 1D array:", scalar + array_1d)
print("1D array shape:", array_1d.shape)

# Broadcasting with 2D array
column_vector = np.array([[1], [2], [3]])
row_vector = np.array([10, 20])

print("Column vector shape:", column_vector.shape)
print("Row vector shape:", row_vector.shape)
print("Broadcasted addition:\n", column_vector + row_vector)


Scalar + 1D array: [6 7 8 9]
1D array shape: (4,)
Column vector shape: (3, 1)
Row vector shape: (2,)
Broadcasted addition:
 [[11 21]
 [12 22]
 [13 23]]


## 5. Array Manipulation
### Reshaping Arrays
Reshaping allows you to change the dimensions of an array without changing its data:


In [ ]:
# Reshape arrays
original = np.arange(12)
print("Original array:", original)
print("Shape:", original.shape)

reshaped = original.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Automatic dimension calculation
auto_reshape = original.reshape(4, -1)  # -1 means "calculate this dimension"
print("Auto reshaped (4, -1):\n", auto_reshape)

# Flatten array
flattened = reshaped.flatten()
print("Flattened:", flattened)

# Transpose
transposed = reshaped.T
print("Transposed:\n", transposed)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Auto reshaped (4, -1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Concatenation
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Vertical stack
vstack_result = np.vstack((arr1, arr2))
print("Vertical stack:\n", vstack_result)

# Horizontal stack
hstack_result = np.hstack((arr1, arr2))
print("Horizontal stack:\n", hstack_result)

# Concatenate with axis parameter
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("Concatenate axis=0:\n", concat_axis0)
print("Concatenate axis=1:\n", concat_axis1)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


## 6. Statistical Operations
NumPy provides comprehensive statistical functions:


### Basic Statistics

In [ ]:
# Statistical functions
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Data:\n", data)
print("Mean:", np.mean(data))
print("Mean along axis 0 (columns):", np.mean(data, axis=0))
print("Mean along axis 1 (rows):", np.mean(data, axis=1))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Sum:", np.sum(data))
print("Median:", np.median(data))


Data:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mean: 6.5
Mean along axis 0 (columns): [5. 6. 7. 8.]
Mean along axis 1 (rows): [ 2.5  6.5 10.5]
Standard deviation: 3.452052529534663
Variance: 11.916666666666666
Minimum: 1
Maximum: 12
Sum: 78
Median: 6.5


In [ ]:
# Statistical functions
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Data:\n", data)
print("Mean:", np.mean(data))
print("Mean along axis 0 (columns):", np.mean(data, axis=0))
print("Mean along axis 1 (rows):", np.mean(data, axis=1))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Sum:", np.sum(data))
print("Median:", np.median(data))


Data:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mean: 6.5
Mean along axis 0 (columns): [5. 6. 7. 8.]
Mean along axis 1 (rows): [ 2.5  6.5 10.5]
Standard deviation: 3.452052529534663
Variance: 11.916666666666666
Minimum: 1
Maximum: 12
Sum: 78
Median: 6.5


In [ ]:
# More statistical functions
sample_data = np.random.normal(50, 15, 1000)  # Mean=50, std=15, 1000 samples

print("Sample statistics:")
print("Mean:", np.mean(sample_data))
print("Median:", np.median(sample_data))
print("Standard deviation:", np.std(sample_data))
print("25th percentile:", np.percentile(sample_data, 25))
print("75th percentile:", np.percentile(sample_data, 75))

# Correlation and covariance
x = np.random.randn(100)
y = 2 * x + np.random.randn(100)  # y is correlated with x

correlation_matrix = np.corrcoef(x, y)
print("Correlation matrix:\n", correlation_matrix)

covariance_matrix = np.cov(x, y)
print("Covariance matrix:\n", covariance_matrix)


## 7. Linear Algebra
NumPy's linear algebra capabilities are essential for scientific computing:


In [ ]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Matrix multiplication
matrix_mult = np.dot(A, B)
print("Matrix multiplication A·B:\n", matrix_mult)

# Alternative syntax (Python 3.5+)
matrix_mult_alt = A @ B
print("Matrix multiplication A@B:\n", matrix_mult_alt)

# Element-wise multiplication
element_mult = A * B
print("Element-wise multiplication:\n", element_mult)



Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix multiplication A·B:
 [[19 22]
 [43 50]]
Matrix multiplication A@B:
 [[19 22]
 [43 50]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]


In [ ]:

A = np.array([[4, 2], [1, 3]])
print("Matrix A:\n", A)

# Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

# Verify inverse: A * A^(-1) should be identity
identity_check = A @ inv_A
print("A * A^(-1) (should be identity):\n", np.round(identity_check, 10))

# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:\n", eigenvecs)

# Solving linear systems: Ax = b
b = np.array([8, 5])
x = np.linalg.solve(A, b)
print("Solution to Ax = b:", x)
print("Verification Ax:", A @ x)


Matrix A:
 [[4 2]
 [1 3]]
Determinant of A: 10.000000000000002
Inverse of A:
 [[ 0.3 -0.2]
 [-0.1  0.4]]
A * A^(-1) (should be identity):
 [[ 1.  0.]
 [-0.  1.]]
Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
Solution to Ax = b: [1.4 1.2]
Verification Ax: [8. 5.]
